#!/bin/bash
#
#PBS -N MakeMasterGrid
#PBS -l walltime=01:00:00
#PBS -l vmem=4gb
#PBS -m bea
#PBS -k oe
#PBS -M jdblg1@le.ac.uk

SHAPELIST=/data/name/Python/PML_shapes.list_v2grid
NAMEFILE=/data/name/Python/PML_NAME_output/low5dayPML_20150501.txt
OUTPUT_GRID=/data/name/Python/PML_master_v2.pkl

# Execute the job code
source /data/name/Python/gridsetup.sh;/data/name/Python/makemastergrid2DEV.py -s $SHAPELIST -n $NAMEFILE -o $OUTPUT_GRID
